version: 1.0.{build}
init:
- ps: Set-WinSystemLocale ja-JP
- ps: Start-Sleep -s 5
- ps: Restart-Computer

install:
- SET PATH=%PATH%;C:\msys64\usr\bin
- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S zip"
- '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars32.bat"'

build_script:
- build.bat
- bytecompile.bat
- archive.bat

test_script:
- run-tests.bat

artifacts:
  - path: _dist\xyzzy-dev.zip
    name: xyzzy-dev
