version: 1.0.{build}
image: Visual Studio 2015

init:
- ps: >-
    Set-WinSystemLocale ja-JP
    Start-Sleep -s 10
    Restart-Computer
    Start-Sleep -s 10

install:
- cmd: >-
    SET PATH=%PATH%;C:\msys64\usr\bin
    C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S zip"
    "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars32.bat"

build_script:
- cmd: >-
    build.bat
    bytecompile.bat
    archive.bat

test_script:
- cmd: run-tests.bat

artifacts:
  - path: _dist\xyzzy-dev.zip
    name: xyzzy-dev
